-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.test_users
(
    github_login text COLLATE pg_catalog."default" NOT NULL,
    github_token text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default",
    avatar text COLLATE pg_catalog."default",
    CONSTRAINT test_users_pkey PRIMARY KEY (github_login)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.test_users
    OWNER to postgres;

GRANT ALL ON TABLE public.test_users TO anon;

GRANT ALL ON TABLE public.test_users TO authenticated;

GRANT ALL ON TABLE public.test_users TO postgres;

GRANT ALL ON TABLE public.test_users TO service_role;
