-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TYPE public.category AS ENUM
    ('SELFIE', 'PORTRAIT', 'ACTION', 'LANDSCAPE', 'GRAPHIC');

ALTER TYPE public.category
    OWNER TO postgres;

CREATE TABLE IF NOT EXISTS public.photos
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    category category,
    github_user text COLLATE pg_catalog."default" NOT NULL,
    created date,
    CONSTRAINT photos_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.photos
    OWNER to postgres;

GRANT ALL ON TABLE public.photos TO anon;

GRANT ALL ON TABLE public.photos TO authenticated;

GRANT ALL ON TABLE public.photos TO postgres;

GRANT ALL ON TABLE public.photos TO service_role;

-- Type: category

-- DROP TYPE IF EXISTS public.category;

-- CREATE TYPE public.category AS ENUM
--     ('SELFIE', 'PORTRAIT', 'ACTION', 'LANDSCAPE', 'GRAPHIC');

-- ALTER TYPE public.category
--     OWNER TO postgres;
