-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

DROP TABLE IF EXISTS public.test_users CASCADE;

ALTER TABLE IF EXISTS public.users DROP COLUMN IF EXISTS id;

ALTER TABLE IF EXISTS public.users
    RENAME id TO github_login;

ALTER TABLE public.users
    ALTER COLUMN github_login TYPE text COLLATE pg_catalog."default";

ALTER TABLE IF EXISTS public.users
    ALTER COLUMN github_login DROP IDENTITY;

ALTER TABLE IF EXISTS public.users
    ALTER COLUMN github_login SET STORAGE EXTENDED;

ALTER TABLE IF EXISTS public.users
    ADD COLUMN github_token text COLLATE pg_catalog."default" NOT NULL;

ALTER TABLE IF EXISTS public.users
    ADD COLUMN avatar text COLLATE pg_catalog."default";
ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT test_users_pkey PRIMARY KEY (github_login);
